profile: cover.out
local-prefix: "github.com/jon-r/stock-service"

threshold:
  #  fixme raise this up at some point
  # (optional; default 0)
  # The minimum coverage that each file should have
  file: 45 # 70

  # (optional; default 0)
  # The minimum coverage that each package should have
  package: 50 # 70

  # (optional; default 0)
  # The minimum total coverage project should have
  total: 70 # 80
