profile: cover.out
local-prefix: "github.com/jon-r/stock-service"

exclude:
  paths:
    - "lambdas/cmd/api-logs"
    - "lambdas/cmd/api-users"
    - "lambdas/internal/utils/test"

threshold:
  file: 75
