name: Go CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature/STK-92-unit-tests

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.2

      - name: Run tests
        run: go test ./lambdas/... -coverprofile=./cover.out -covermode=atomic -coverpkg=./lambdas/...

      - name: check test coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          config: ./.testcoverage.yml
