name: Go CI/CD Pipeline

on:
  push:
    branches:
      - main

  pull_request_target:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.2

      - name: Run tests
        run: go test ./...
        working-directory: lambdas
